version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
